// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Whistl3rApi.Data;

#nullable disable

namespace Whistl3rApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260310115647_AddGameLengthinMinutes")]
    partial class AddGameLengthinMinutes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Whistl3rApi.Models.AgeLevel", b =>
                {
                    b.Property<int>("AgeLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("age_level_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AgeLevelId"));

                    b.Property<string>("AgeLevelName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("age_level_name");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int?>("MaxAge")
                        .HasColumnType("integer")
                        .HasColumnName("max_age");

                    b.Property<int?>("MinAge")
                        .HasColumnType("integer")
                        .HasColumnName("min_age");

                    b.Property<int>("SportId")
                        .HasColumnType("integer")
                        .HasColumnName("sport_id");

                    b.HasKey("AgeLevelId");

                    b.ToTable("age_levels");
                });

            modelBuilder.Entity("Whistl3rApi.Models.Assignor", b =>
                {
                    b.Property<int>("AssignorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("assignor_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AssignorId"));

                    b.Property<bool>("IsSuperAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_super_admin");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("AssignorId");

                    b.ToTable("assignors");
                });

            modelBuilder.Entity("Whistl3rApi.Models.AssignorOrganization", b =>
                {
                    b.Property<int>("AssignorOrganizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("assignor_organization_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AssignorOrganizationId"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<int?>("AssignedBy")
                        .HasColumnType("integer")
                        .HasColumnName("assigned_by");

                    b.Property<int>("AssignorId")
                        .HasColumnType("integer")
                        .HasColumnName("assignor_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer")
                        .HasColumnName("organization_id");

                    b.Property<string>("RoleLevel")
                        .HasColumnType("text")
                        .HasColumnName("role_level");

                    b.HasKey("AssignorOrganizationId");

                    b.HasIndex("AssignorId");

                    b.ToTable("assignor_organizations");
                });

            modelBuilder.Entity("Whistl3rApi.Models.Coach", b =>
                {
                    b.Property<int>("CoachId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("coach_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CoachId"));

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("CoachId");

                    b.ToTable("coaches");
                });

            modelBuilder.Entity("Whistl3rApi.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("game_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GameId"));

                    b.Property<int>("AgeLevelId")
                        .HasColumnType("integer")
                        .HasColumnName("age_level_id");

                    b.Property<string>("AwayTeam")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("away_team");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("GameDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("game_date");

                    b.Property<int?>("GameLengthMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("game_length_minutes");

                    b.Property<int>("GameStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("game_status_id");

                    b.Property<TimeSpan>("GameTime")
                        .HasColumnType("interval")
                        .HasColumnName("game_time");

                    b.Property<string>("HomeTeam")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("home_team");

                    b.Property<int?>("LeagueId")
                        .HasColumnType("integer")
                        .HasColumnName("league_id");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer")
                        .HasColumnName("organization_id");

                    b.Property<int?>("OverrideGameLengthMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("override_game_length_minutes");

                    b.Property<int?>("PayScaleRuleId")
                        .HasColumnType("integer")
                        .HasColumnName("pay_scale_rule_id");

                    b.Property<int?>("TournamentId")
                        .HasColumnType("integer")
                        .HasColumnName("tournament_id");

                    b.Property<int>("VenueId")
                        .HasColumnType("integer")
                        .HasColumnName("venue_id");

                    b.HasKey("GameId");

                    b.HasIndex("GameDate");

                    b.HasIndex("GameStatusId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("VenueId");

                    b.ToTable("games", (string)null);
                });

            modelBuilder.Entity("Whistl3rApi.Models.GameAssignment", b =>
                {
                    b.Property<int>("GameAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("game_assignment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GameAssignmentId"));

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<int>("AssignedBy")
                        .HasColumnType("integer")
                        .HasColumnName("assigned_by");

                    b.Property<string>("AssignmentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("assignment_status");

                    b.Property<decimal?>("BasePayAmount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("base_pay_amount");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<decimal?>("DistanceKm")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("distance_km");

                    b.Property<decimal?>("FinalPayAmount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("final_pay_amount");

                    b.Property<int>("GameId")
                        .HasColumnType("integer")
                        .HasColumnName("game_id");

                    b.Property<decimal?>("MultiplierApplied")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("multiplier_applied");

                    b.Property<int>("OfficialId")
                        .HasColumnType("integer")
                        .HasColumnName("official_id");

                    b.Property<int>("PositionId")
                        .HasColumnType("integer")
                        .HasColumnName("position_id");

                    b.Property<decimal?>("TravelPayAmount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("travel_pay_amount");

                    b.HasKey("GameAssignmentId");

                    b.HasIndex("AssignmentStatus");

                    b.HasIndex("GameId");

                    b.HasIndex("OfficialId");

                    b.ToTable("game_assignments", (string)null);
                });

            modelBuilder.Entity("Whistl3rApi.Models.GameClaim", b =>
                {
                    b.Property<int>("GameClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("game_claim_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GameClaimId"));

                    b.Property<string>("ClaimStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("claim_status");

                    b.Property<DateTime>("ClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at");

                    b.Property<int>("GameId")
                        .HasColumnType("integer")
                        .HasColumnName("game_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("OfficialId")
                        .HasColumnType("integer")
                        .HasColumnName("official_id");

                    b.Property<int>("PositionId")
                        .HasColumnType("integer")
                        .HasColumnName("position_id");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<int?>("ReviewedBy")
                        .HasColumnType("integer")
                        .HasColumnName("reviewed_by");

                    b.HasKey("GameClaimId");

                    b.HasIndex("ClaimStatus");

                    b.HasIndex("GameId");

                    b.HasIndex("OfficialId");

                    b.ToTable("game_claims", (string)null);
                });

            modelBuilder.Entity("Whistl3rApi.Models.GameStatus", b =>
                {
                    b.Property<int>("GameStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("game_status_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GameStatusId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GameStatusName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("game_status_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.HasKey("GameStatusId");

                    b.ToTable("game_status");
                });

            modelBuilder.Entity("Whistl3rApi.Models.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GroupId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("group_name");

                    b.Property<int>("SportId")
                        .HasColumnType("integer")
                        .HasColumnName("sport_id");

                    b.HasKey("GroupId");

                    b.ToTable("official_groups");
                });

            modelBuilder.Entity("Whistl3rApi.Models.GroupMember", b =>
                {
                    b.Property<int>("GroupMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("group_member_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GroupMemberId"));

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<int>("OfficialId")
                        .HasColumnType("integer")
                        .HasColumnName("official_id");

                    b.HasKey("GroupMemberId");

                    b.HasIndex("GroupId");

                    b.ToTable("group_members");
                });

            modelBuilder.Entity("Whistl3rApi.Models.League", b =>
                {
                    b.Property<int>("LeagueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("league_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LeagueId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LeagueName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("league_name");

                    b.Property<string>("Season")
                        .HasColumnType("text")
                        .HasColumnName("season");

                    b.Property<int>("SportId")
                        .HasColumnType("integer")
                        .HasColumnName("sport_id");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.HasKey("LeagueId");

                    b.HasIndex("LeagueName");

                    b.ToTable("leagues", (string)null);
                });

            modelBuilder.Entity("Whistl3rApi.Models.LeagueOrganization", b =>
                {
                    b.Property<int>("LeagueOrganizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("league_organization_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LeagueOrganizationId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<int>("LeagueId")
                        .HasColumnType("integer")
                        .HasColumnName("league_id");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer")
                        .HasColumnName("organization_id");

                    b.HasKey("LeagueOrganizationId");

                    b.HasIndex("LeagueId");

                    b.ToTable("league_organizations");
                });

            modelBuilder.Entity("Whistl3rApi.Models.Mentor", b =>
                {
                    b.Property<int>("MentorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("mentor_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MentorId"));

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("MentorId");

                    b.ToTable("mentors");
                });

            modelBuilder.Entity("Whistl3rApi.Models.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("message_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MessageId"));

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("MessageBody")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_body");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<int?>("RecipientGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("recipient_group_id");

                    b.Property<int?>("RecipientUserId")
                        .HasColumnType("integer")
                        .HasColumnName("recipient_user_id");

                    b.Property<int>("SenderUserId")
                        .HasColumnType("integer")
                        .HasColumnName("sender_user_id");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("subject");

                    b.HasKey("MessageId");

                    b.ToTable("messages");
                });

            modelBuilder.Entity("Whistl3rApi.Models.Official", b =>
                {
                    b.Property<int>("OfficialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("official_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OfficialId"));

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("OfficialId");

                    b.ToTable("officials");
                });

            modelBuilder.Entity("Whistl3rApi.Models.Organization", b =>
                {
                    b.Property<int>("OrganizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("organization_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrganizationId"));

                    b.Property<string>("AddressLine1")
                        .HasColumnType("text")
                        .HasColumnName("address_line1");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("text")
                        .HasColumnName("address_line2");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("text")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("text")
                        .HasColumnName("contact_phone");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("OrganizationAbbr")
                        .HasColumnType("text")
                        .HasColumnName("organization_abbr");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("organization_name");

                    b.Property<string>("OrganizationType")
                        .HasColumnType("text")
                        .HasColumnName("organization_type");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text")
                        .HasColumnName("postal_code");

                    b.Property<string>("StateProvince")
                        .HasColumnType("text")
                        .HasColumnName("state_province");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Website")
                        .HasColumnType("text")
                        .HasColumnName("website");

                    b.HasKey("OrganizationId");

                    b.HasIndex("OrganizationName");

                    b.ToTable("organizations");
                });

            modelBuilder.Entity("Whistl3rApi.Models.Parent", b =>
                {
                    b.Property<int>("ParentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ParentId"));

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("ParentId");

                    b.ToTable("parents");
                });

            modelBuilder.Entity("Whistl3rApi.Models.PayScaleRule", b =>
                {
                    b.Property<int>("PayScaleRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pay_scale_rule_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PayScaleRuleId"));

                    b.Property<int?>("AgeLevelId")
                        .HasColumnType("integer")
                        .HasColumnName("age_level_id");

                    b.Property<decimal>("BasePayAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("base_pay_amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int?>("LeagueId")
                        .HasColumnType("integer")
                        .HasColumnName("league_id");

                    b.Property<decimal>("PayMultiplier")
                        .HasColumnType("numeric")
                        .HasColumnName("pay_multiplier");

                    b.Property<decimal>("PayPerKm")
                        .HasColumnType("numeric")
                        .HasColumnName("pay_per_km");

                    b.Property<int?>("PositionId")
                        .HasColumnType("integer")
                        .HasColumnName("position_id");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<int?>("SportId")
                        .HasColumnType("integer")
                        .HasColumnName("sport_id");

                    b.HasKey("PayScaleRuleId");

                    b.ToTable("pay_scale_rules");
                });

            modelBuilder.Entity("Whistl3rApi.Models.PerformanceReview", b =>
                {
                    b.Property<int>("PerformanceReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("performance_review_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PerformanceReviewId"));

                    b.Property<string>("AdditionalComments")
                        .HasColumnType("text")
                        .HasColumnName("additional_comments");

                    b.Property<string>("AreasForImprovement")
                        .HasColumnType("text")
                        .HasColumnName("areas_for_improvement");

                    b.Property<int?>("Communication")
                        .HasColumnType("integer")
                        .HasColumnName("communication");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("GameAssignmentId")
                        .HasColumnType("integer")
                        .HasColumnName("game_assignment_id");

                    b.Property<int?>("GameManagement")
                        .HasColumnType("integer")
                        .HasColumnName("game_management");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<int?>("KnowledgeOfRules")
                        .HasColumnType("integer")
                        .HasColumnName("knowledge_of_rules");

                    b.Property<int?>("OverallRating")
                        .HasColumnType("integer")
                        .HasColumnName("overall_rating");

                    b.Property<int?>("Positioning")
                        .HasColumnType("integer")
                        .HasColumnName("positioning");

                    b.Property<int?>("Professionalism")
                        .HasColumnType("integer")
                        .HasColumnName("professionalism");

                    b.Property<int>("ReviewerId")
                        .HasColumnType("integer")
                        .HasColumnName("reviewer_id");

                    b.Property<string>("Strengths")
                        .HasColumnType("text")
                        .HasColumnName("strengths");

                    b.HasKey("PerformanceReviewId");

                    b.ToTable("performance_reviews");
                });

            modelBuilder.Entity("Whistl3rApi.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsSystemRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system_role");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("roles");
                });

            modelBuilder.Entity("Whistl3rApi.Models.Sport", b =>
                {
                    b.Property<int>("SportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("sport_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SportId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("SportCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sport_code");

                    b.Property<string>("SportName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sport_name");

                    b.HasKey("SportId");

                    b.HasIndex("SportName")
                        .IsUnique();

                    b.ToTable("sports", (string)null);
                });

            modelBuilder.Entity("Whistl3rApi.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("email_verified");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<bool>("PhoneVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_verified");

                    b.Property<Guid?>("ResetPasswordGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("reset_password_guid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UserType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("user_type");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.HasIndex("UserType");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Whistl3rApi.Models.UserRole", b =>
                {
                    b.Property<int>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_role_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserRoleId"));

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("UserRoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("user_roles");
                });

            modelBuilder.Entity("Whistl3rApi.Models.Venue", b =>
                {
                    b.Property<int>("VenueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("venue_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VenueId"));

                    b.Property<string>("AddressLine1")
                        .HasColumnType("text")
                        .HasColumnName("address_line1");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("text")
                        .HasColumnName("address_line2");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric")
                        .HasColumnName("longitude");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer")
                        .HasColumnName("organization_id");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text")
                        .HasColumnName("postal_code");

                    b.Property<string>("StateProvince")
                        .HasColumnType("text")
                        .HasColumnName("state_province");

                    b.Property<string>("Timezone")
                        .HasColumnType("text")
                        .HasColumnName("timezone");

                    b.Property<string>("VenueName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("venue_name");

                    b.HasKey("VenueId");

                    b.HasIndex("VenueName");

                    b.ToTable("venues", (string)null);
                });

            modelBuilder.Entity("Whistl3rApi.Models.AssignorOrganization", b =>
                {
                    b.HasOne("Whistl3rApi.Models.Assignor", "Assignor")
                        .WithMany("AssignorOrganizations")
                        .HasForeignKey("AssignorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignor");
                });

            modelBuilder.Entity("Whistl3rApi.Models.Game", b =>
                {
                    b.HasOne("Whistl3rApi.Models.GameStatus", "GameStatus")
                        .WithMany("Games")
                        .HasForeignKey("GameStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameStatus");
                });

            modelBuilder.Entity("Whistl3rApi.Models.GameAssignment", b =>
                {
                    b.HasOne("Whistl3rApi.Models.Game", "Game")
                        .WithMany("Assignments")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Whistl3rApi.Models.GameClaim", b =>
                {
                    b.HasOne("Whistl3rApi.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Whistl3rApi.Models.GroupMember", b =>
                {
                    b.HasOne("Whistl3rApi.Models.Group", "Group")
                        .WithMany("GroupMembers")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Whistl3rApi.Models.LeagueOrganization", b =>
                {
                    b.HasOne("Whistl3rApi.Models.League", "League")
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("Whistl3rApi.Models.UserRole", b =>
                {
                    b.HasOne("Whistl3rApi.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Whistl3rApi.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Whistl3rApi.Models.Assignor", b =>
                {
                    b.Navigation("AssignorOrganizations");
                });

            modelBuilder.Entity("Whistl3rApi.Models.Game", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("Whistl3rApi.Models.GameStatus", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("Whistl3rApi.Models.Group", b =>
                {
                    b.Navigation("GroupMembers");
                });

            modelBuilder.Entity("Whistl3rApi.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Whistl3rApi.Models.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
