FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["services/Games/Games.csproj", "services/Games/"]
RUN dotnet restore "services/Games/Games.csproj"
COPY services/Games/ services/Games/
WORKDIR "/src/services/Games"
RUN dotnet build "Games.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Games.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Games.dll"]
