FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["services/Games/Games.csproj", "services/Games/"]
RUN dotnet restore "services/Games/Games.csproj"
COPY services/Games/ services/Games/
WORKDIR "/src/services/Games"
RUN dotnet publish "Games.csproj" -c Release -o /app/publish

FROM public.ecr.aws/lambda/dotnet:8 AS runtime
WORKDIR /var/task
COPY --from=build /app/publish .
CMD ["Games"]
