FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["services/PayScale/PayScale.csproj", "services/PayScale/"]
RUN dotnet restore "services/PayScale/PayScale.csproj"
COPY services/PayScale/ services/PayScale/
WORKDIR "/src/services/PayScale"
RUN dotnet build "PayScale.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "PayScale.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "PayScale.dll"]
