FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["services/PayScale/PayScale.csproj", "services/PayScale/"]
RUN dotnet restore "services/PayScale/PayScale.csproj"
COPY services/PayScale/ services/PayScale/
WORKDIR "/src/services/PayScale"
RUN dotnet publish "PayScale.csproj" -c Release -o /app/publish

FROM public.ecr.aws/lambda/dotnet:8 AS runtime
WORKDIR /var/task
COPY --from=build /app/publish .
CMD ["PayScale"]
