FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["services/Groups/Groups.csproj", "services/Groups/"]
RUN dotnet restore "services/Groups/Groups.csproj"
COPY services/Groups/ services/Groups/
WORKDIR "/src/services/Groups"
RUN dotnet build "Groups.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Groups.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Groups.dll"]
