FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["services/Organizations/Organizations.csproj", "services/Organizations/"]
RUN dotnet restore "services/Organizations/Organizations.csproj"
COPY services/Organizations/ services/Organizations/
WORKDIR "/src/services/Organizations"
RUN dotnet build "Organizations.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Organizations.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Organizations.dll"]
