FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["services/Users/Users.csproj", "services/Users/"]
RUN dotnet restore "services/Users/Users.csproj"
COPY services/Users/ services/Users/
WORKDIR "/src/services/Users"
RUN dotnet publish "Users.csproj" -c Release -o /app/publish

FROM public.ecr.aws/lambda/dotnet:8 AS runtime
WORKDIR /var/task
COPY --from=build /app/publish .
CMD ["Users"]
