FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["services/Assignors/Assignors.csproj", "services/Assignors/"]
RUN dotnet restore "services/Assignors/Assignors.csproj"
COPY services/Assignors/ services/Assignors/
WORKDIR "/src/services/Assignors"
RUN dotnet publish "Assignors.csproj" -c Release -o /app/publish

FROM public.ecr.aws/lambda/dotnet:8 AS runtime
WORKDIR /var/task
COPY --from=build /app/publish .
CMD ["Assignors"]
