FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["services/Organizations/Organizations.csproj", "services/Organizations/"]
RUN dotnet restore "services/Organizations/Organizations.csproj"
COPY services/Organizations/ services/Organizations/
WORKDIR "/src/services/Organizations"
RUN dotnet publish "Organizations.csproj" -c Release -o /app/publish

FROM public.ecr.aws/lambda/dotnet:8 AS runtime
WORKDIR /var/task
COPY --from=build /app/publish .
CMD ["Organizations"]
