FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["services/Communication/Communication.csproj", "services/Communication/"]
RUN dotnet restore "services/Communication/Communication.csproj"
COPY services/Communication/ services/Communication/
WORKDIR "/src/services/Communication"
RUN dotnet publish "Communication.csproj" -c Release -o /app/publish

FROM public.ecr.aws/lambda/dotnet:8 AS runtime
WORKDIR /var/task
COPY --from=build /app/publish .
CMD ["Communication"]
