FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["services/Reviews/Reviews.csproj", "services/Reviews/"]
RUN dotnet restore "services/Reviews/Reviews.csproj"
COPY services/Reviews/ services/Reviews/
WORKDIR "/src/services/Reviews"
RUN dotnet publish "Reviews.csproj" -c Release -o /app/publish

FROM public.ecr.aws/lambda/dotnet:8 AS runtime
WORKDIR /var/task
COPY --from=build /app/publish .
CMD ["Reviews"]
