FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["services/Reviews/Reviews.csproj", "services/Reviews/"]
RUN dotnet restore "services/Reviews/Reviews.csproj"
COPY services/Reviews/ services/Reviews/
WORKDIR "/src/services/Reviews"
RUN dotnet build "Reviews.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Reviews.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Reviews.dll"]
