FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["services/Groups/Groups.csproj", "services/Groups/"]
RUN dotnet restore "services/Groups/Groups.csproj"
COPY services/Groups/ services/Groups/
WORKDIR "/src/services/Groups"
RUN dotnet publish "Groups.csproj" -c Release -o /app/publish

FROM public.ecr.aws/lambda/dotnet:8 AS runtime
WORKDIR /var/task
COPY --from=build /app/publish .
CMD ["Groups"]
