FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["services/Assignors/Assignors.csproj", "services/Assignors/"]
RUN dotnet restore "services/Assignors/Assignors.csproj"
COPY services/Assignors/ services/Assignors/
WORKDIR "/src/services/Assignors"
RUN dotnet build "Assignors.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Assignors.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Assignors.dll"]
